### ISSUE TITLE
Sculpt USB stick at hd1: screen full of (?)s

### ISSUE THREAD

**Issue by dckc** [alex-ab/g2fg#1]
Thanks for this nifty tool that deals with so many constraints. Unfortunately, I ran into one more.

When I put the [Sculpt OS 20.02 image](https://genode.org/download/sculpt)<sup>[img](#img)</sup> on a USB stick into my HP ENVY 15z-j100 Notebook PC and booted it up, I got a few lines of question marks with circles around them<sup>[qmark](#qmark)</sup>

The solution was to change this line in the `grub.cfg` on partition 2...

https://github.com/alex-ab/g2fg/blob/1b148c6479f2c1f96fa1a1ae66c8cd3bbae538f2/create_grub2_head_image#L101

to:
```
 set root=(hd1,3)
```

because the internal disk took the `hd0` spot.

But diagnosing that was pretty tricky. At first I noticed that the enter key produced another line with a few (?)s like a prompt. I tried various commands at random and noticed that `clear` worked as expected, at which point I realized this was probably grub. I managed to figure out that `terminal_output console` would fix the (?) situation, so I tried some commands from the `grub.cfg` files. `insmod multiboot2` failed with file not found, referring to something in `x86_64-efi` but tab-completion showed an `i386-pc` directory. Fixing the file path resulted in `invalid arch-dependent ELF magic`. I finally understood that there were 2 levels of `grub.cfg` going on and changed `hd0` to `hd1` in the 1st one and voila! all was well.

<sup>qmark</sup> the character grub shows when its font is missing; a bit like [another grub boot screen with missing glyphs from Nov 2010](https://askubuntu.com/a/11852) but my screen had no legible characters; only (?)s.

<sup>img</sup> https://genode.org/files/sculpt/sculpt-20-02.img SHA256 b37dc12c2d8c0b4ddd17902a03de3759ca598a1cfde88f2c10472b41c0a5cac5

**Comment by alex-ab** [comment]
Thanks for the report.

The missing fonts are more then less intentionally, in order to reduce image size (~2.5MB). If you build images yourself for debugging purposes, you may add the unicode.pf2 file by inspecting tool/run/boot_dir/nova for the out commented lines regarding pf2.

> set root=(hd1,3)

Mmmh, if we would find a way to modify with grub2 scripting primitives the $root var containing something like (hdX,1) to (hdX,3) we could solve the issue in general.

**Comment by dckc** [comment]
> The missing fonts are more then less intentionally, in order to reduce image size (~2.5MB). If you build images yourself for debugging purposes, you may add the unicode.pf2 file by inspecting tool/run/boot_dir/nova for the out commented lines regarding pf2.

I just used `terminal_output console` rather than `gfxmode`. Any reason not to do that?

**Comment by dckc** [comment]
p.s. oh... I guess you want `gfxmode` for the splash graphic.

**Comment by alex-ab** [comment]
> p.s. oh... I guess you want gfxmode for the splash graphic.

Yes.

Can you please try above commits ? For me it still works, but now should cover your case to.

**Comment by dckc** [comment]
Thanks for working out the details!

I'm not sure how to try it out. Does it involve building all of Sculpt?

**Comment by alex-ab** [comment]
> I'm not sure how to try it out. Does it involve building all of Sculpt?

Yes, actually more downloading then building, but, yes. The instructions are described by
https://genode.org/documentation/articles/sculpt-20-02#Building_the_boot_image. After the git checkout you would have to add my genode repository to your git checkout and cherrypick the commit a0d5a602d917d372f9cc8b1a609db34540ffeb51, before proceeding with the 2. step of the description.

If you can't/don't want to handle it, I can also build the image for you.
